
# CLAIM BOUNDS COMMAND SETTINGs
MASTER_POINT_PARTICLE_COUNT: 60
POINT_PARTICLE_COUNT: 30
POINT_LINE_PARTICLE_COUNT: 15
POINT_SIZE: 5.0
LINE_SIZE: 2.5
# Set to AIR to disable this
CORONER_BLOCK: GLOWSTONE
LINE_BLOCk: GLASS
CORONER_POINT_BLOCK: GOLD_BLOCK
# How long to show the block border for
SHOW_FOR_SECONDS: 5

# CLAIM COMMAND SETTINGS

ALLOW_MAX_SIZE_BYPASS: true

# This will be cubed, set to 0 to disable this
MAX_SIZE: 35

# SAFE-LIST

# Set this to true to enable this
SAFELIST_ON: false

# Modes:
# KICK: Kick the player
# BAN: Ban the player
# BAN_IP: Ban the player's ip
# LOG_ONLY: Log the player
SAFELIST_MODE: KICK

# Message
# Format with {xxx}
# Replace xxx with one of the following:
# black
# gold
# gray
# blue
# green
# aqua
# red
# light_purple
# yellow
# white
# bold
# italic
# reset
# player
# newline
SAFELIST_MESSAGE: "{red}You are not {bold}allowed{reset}{red} on this server!{newline}{reset}{gold}If this is your first time seeing this ask the server admin to add you to the Easy Guard safe-list in the config!"

ALLOWED_PLAYERS:
  - "ENTER_USERNAMES_HERE"
  - "LIKE_THIS"

# CREEPER GUARD

# Default: true
# This will enable and/or disable the plugin
CreeperGuardActive: true

# Default: true
# If this is set to true, when a creeper explodes it will not remove the entity
CreeperGuardRemoveCreeperEntityOnExplode: true

# Default: false
# To show smoke particles when a creeper explodes
CreeperGuardShowParticles: false

# Default: 25
# The number of smoke particles to show
CreeperGuardParticleCount: 25

# Default: true
# Disables the damage when a creeper explodes
CreeperGuardDisableDamage: true

# Default: true
# When enabled it will play a pop sound when a creeper explodes
CreeperGuardPlaySound: true

# ENDERMAN GUARD

# Default: true
# Set this to false to disable this
ENDERMANGUARD_ON: true

# TNT GUARD

# Default: true
# Set this to false to disable this
TNTGUARD_ON: true

# Default: false
# To show smoke particles when a something explodes
TNTGuardShowParticles: false

# Default: 25
# The number of smoke particles to show
TNTGuardParticleCount: 25

# REKILL GUARD

# Default: true
# Set this to false to disable this
KILLREGUARD_Active: true

# FLOW GUARD
# WARNING THIS CAN CAUSE LOTS OF LAG!!!

# Default: true
FLOWGUARD_ACTIVE: true

# ANTI-SPAM

# Default: true
ANTI_SPAM_ACTIVE: true

ANTI_SPAM_WARNING_COUNT: 3

# Modes:
# KICK: Kick the player
# BAN: Ban the player
# BAN_IP: Ban the player's ip
# LOG_ONLY: Log the player
ANTI_SPAM_ACTION: KICK

# USER DATA - DO NOT CHANGE

data:
