name: EasyGuard
version: '${project.version}'
main: github.aixoio.easyguard.EasyGuard
api-version: 1.19
authors: [aixoio]
depend:
  - WorldGuard
  - WorldEdit
commands:
  claim:
    description: You can use this command to claim land
    usage: /<command> <name> <x> <y> <z> <x> <y> <z>
    permission: easyguard.claim
  claims:
    description: You can use this command to see who has claimed land
    usage: /<command>
    permission: easyguard.claims
  current-claim:
    description: Tells you all of the claims you are currently in
    usage: /<command>
    permission: easyguard.current-claim
  trust:
    description: Lets you trust and untrust players from your claims
    usage: /<command> [add|remove] [options]
    permission: easyguard.trust
  delete-claim:
    description: Lets players delete claims
    usage: /<command> [claim-name]
    permission: easyguard.delete-claim
    aliases:
      - remove-claim
  flag:
    description: Lets you control flags on your claims
    usage: /<command> [list|add|remove|current|reset] [options]
    permission: easyguard.flag
    aliases:
      - flags
  claim-bounds:
    description: Shows the bounds of the current claim/s
    usage: /<command>
    permission: easyguard.bounds
permissions:
  easyguard.claim:
    description: Gives access to /claim
    default: true
  easyguard.claims:
    description: Gives access to /claims
    default: true
  easyguard.current-claim:
    description: Gives access to /current-claim
    default: true
  easyguard.trust:
    description: Gives access to /trust
    default: true
  easyguard.delete-claim:
    description: Gives access to /delete-claim
    default: true
  easyguard.flag:
    description: Gives access to /flag and /flags
    default: true
  easyguard.claim-bounds:
    description: Gives access to /claim-bounds
    default: true
  easyguard.size-bypass:
    description: Lets plays bypass the claim size limit if one is set
    default: op
  easyguard.safelist-bypass:
    description: Lets players bypass the Safe-list
    default: op
