name: EasyGuard
version: '${project.version}'
main: github.aixoio.easyguard.EasyGuard
api-version: 1.19
authors: [aixoio]
depend:
  - WorldGuard
  - WorldEdit
commands:
  claim:
    description: You can use this command to claim land
    usage: /<command> <name> <x> <y> <z> <x> <y> <z>
    permission: easyguard.claim
  claims:
    description: You can use this command to see who has claimed land
    usage: /<command>
    permission: easyguard.claims
  current-claim:
    description: Tells you all of the claims you are currently in
    usage: /<command>
    permission: easyguard.current-claim
  trust:
    description: Lets you trust and untrust players from your claims
    usage: /<command> [add|remove] [options]
    permission: easyguard.trust
  delete-claim:
    description: Lets players delete claims
    usage: /<command> [claim-name]
    permission: easyguard.delete-claim
    aliases:
      - remove-claim
  flag:
    description: Lets you control flags on your claims
    usage: /<command> [list|add|remove] [options]
    permission: easyguard.flag
    aliases:
      - flags
