name: EasyGuard
version: '${project.version}'
main: github.aixoio.easyguard.EasyGuard
api-version: 1.19
authors: [aixoio]
depend:
  - WorldGuard
  - WorldEdit
commands:
  claim:
    description: You can use this command to claim land
    usage: /<command> <name> <x> <y> z> <x> <y> <z>
    permission: easyguard.claim
